global:
  scrape_interval: 30s

rule_files:
  - alert.yml

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets: ['alertmanager:9093'] # Mettre IP car 'alertmanager:9093' ne marche pas pour l'api endpoint


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'crowdsec_myMachine'
    static_configs:
      - targets: ['192.168.1.1:6060']

