server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.5:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: webserver
          __path__: /var/log/*log

  - job_name: webserver
    static_configs:
      - targets:
          - localhost
        labels:
          job: webserver
          host: webserver
          __path__: /var/log/nginx/*log

