services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_app
    restart: always
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.0-fpm-alpine
    container_name: wordpress_app
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_app
    restart: always

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile 
    container_name: wordpress_nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - nginx_logs:/var/log/nginx
    networks:
      - wp_app
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - nginx_logs:/var/log/nginx
      - ./config/promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - nginx
    networks:
      - wp_app

volumes:
  db_data:
  wordpress_data:
  nginx_logs:
    
networks:
  wp_app:
    name: wp_app
