apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.1.5:9090
    editable: true
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://192.168.1.5:3100
    version: 1
    editable: true
    isDefault: false
