global:
  smtp_smarthost: 'mail.smtp2go.com:587'
  smtp_from: 'ne-pas-repondre@veldes.fr'
  smtp_auth_username: 'veldes'
  smtp_auth_password: '938o3hGMmDaXNZFV'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'bouzidi.idris42@gmail.com'
        send_resolved: true

